### ISSUE TITLE
请教怎么学习后端

### ISSUE THREAD

**Issue by fEyebrow** [JailBreakC/react-redux-wechat#1]
看阮一峰老师的flex布局教程时，发现你的prokect。尤其是你的博客，真的很酷炫。

最近，我在react的技术栈。react和redux都有一定的了解，并写了一个小项目。但对后端和node.js不了解，能推荐一下学习途径吗？我现在是打算跟threehouse的全栈课来学习的。但是总觉得，光学这些教程很不够。想请教一下后端的学习途径。

另外，应届毕业生要什么水平才能进头条的前端？

**Comment by JailBreakC** [comment]
我不太清楚 threehouse 上面的课程安排的是啥样子
一般来说，比较好的课程都会将一个项目作为实例，结合基础知识一起来讲解，到最后做出一个完整的项目。这样从基础知识到应用能力都会有一个提升。

我建议在学的时候，同时自己上手做一个小项目，比如说一个带有数据库存储，后台管理功能的博客，这样就可以很好的结合到你学过的react redux，然后配合 node.js 来写 restful api。功能从简单开始，一步一步增加。同时可以参照一些成熟的开源项目，比如 Ghost ，看看别人怎么设计的功能。

当你学了一段时间，做出来的项目也差不多处于一个可用状态了。面试投简历之前，尽量的将这个项目完善到一个较高的水平，然后复习前端的基础知识，比如面向对象，简单的算法，http协议，浏览器缓存机制等，做到熟练掌握。再去了解一下你所用过的框架的实现原理，设计模式。
综合起来，素质达到一个较高的水平就差不多了

**Comment by fEyebrow** [comment]
我一周前就在写博客的前端。但是遇到各种问题，尤其是css的知识。以为会写javascript就行了。导致原先计划好的功能和界面草草地实现。现在回过头来学css和动画，想问下有没有好的实践？

另外文章的排版最让人头痛。实现在线写文章功能的时候才发觉要用到富文本。能推荐一下相关的实践资料吗？
谢谢。

**Comment by JailBreakC** [comment]
不会就学嘛，CSS 入门的话看看文档就 OK 了。

富文本编辑这块会比较复杂，你可以直接用开源的编辑器

**Comment by fEyebrow** [comment]
谢谢
